# Generated by Django 5.2 on 2025-11-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='identificationNumber',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(db_index=True, max_length=50)),
                ('identificationNumber', models.CharField(db_index=True, max_length=50)),
                ('issued', models.DateField()),
                ('dueDate', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('vat', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_buyerInvoices', to='invoices.person')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_sellerInvoices', to='invoices.person')),
            ],
        ),
    ]
