# Generated by Django 5.2 on 2025-11-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_person_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='identificationNumber',
        ),
    ]
