# Generated by Django 5.2 on 2025-11-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_identificationnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
