# Generated by Django 5.2 on 2025-11-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='deleted',
        ),
    ]
