# Generated by Django 5.2 on 2025-11-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='buyer',
            new_name='buyerID',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='seller',
            new_name='sellerID',
        ),
    ]
