# Generated by Django 5.2 on 2025-11-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_rename_buyer_invoice_buyerid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='buyerID',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sellerID',
            new_name='seller',
        ),
    ]
